service:
  889:  # 游戏服务
    service_id: "889"
    service_code: "889"
    service_name: "Gold Finger"
    version: 1
    merchant_id: 52
    share_key: "8f83602cd9f1425ff98b6615cd908c0995354cf1"
    amount: "450"
    period: "604800"
    aoc_url: "http://migpay.com/managed_subscriptions/new"
    contract_length: "infinite"
    item_description: "Gold Finger,a unique entertainment center."
    content_url: "http://muk.g0finger.com?s="
    register_url: "http://muk.g0finger.com/adduser?username={user_name}"
    unsub_success_url: "http://muk.g0finger.com/unsub/success"
    unsub_failed_url: "http://muk.g0finger.com/unsub/failed"
    limit_sub_num: 50
    camp_id: 3
  889-Vodafone:
    service_id: "889-Vodafone"
    service_code: "889"
    service_name: "Gold Finger"
    version: 1
    merchant_id: 52
    share_key: "8f83602cd9f1425ff98b6615cd908c0995354cf1"
    amount: "450"
    period: "604800"
    aoc_url: "http://migpay.com/managed_subscriptions/new"
    contract_length: "infinite"
    item_description: "Gold Finger,a unique entertainment center."
    content_url: "http://muk.g0finger.com?s="
    register_url: "http://muk.g0finger.com/adduser?username={user_name}"
    unsub_success_url: "http://muk.g0finger.com/unsub/success"
    unsub_failed_url: "http://muk.g0finger.com/unsub/failed"
    limit_sub_num: 50
    camp_id: 3
  889-Three:
    service_id: "889-Three"
    service_code: "889"
    service_name: "Gold Finger"
    version: 1
    merchant_id: 52
    share_key: "8f83602cd9f1425ff98b6615cd908c0995354cf1"
    amount: "450"
    period: "604800"
    aoc_url: "http://migpay.com/managed_subscriptions/new"
    contract_length: "infinite"
    item_description: "Gold Finger,a unique entertainment center."
    content_url: "http://muk.g0finger.com?s="
    register_url: "http://muk.g0finger.com/adduser?username={user_name}"
    unsub_success_url: "http://muk.g0finger.com/unsub/success"
    unsub_failed_url: "http://muk.g0finger.com/unsub/failed"
    limit_sub_num: 50
    camp_id: 4
  892:
    service_id: "892"
    service_code: "892"
    service_name: "Fit Body"
    version: 1
    merchant_id: 52
    share_key: "d81aaca1d338aa857f076171ef251775d019e738"
    amount: "450"
    period: "604800"
    aoc_url: "http://migpay.com/managed_subscriptions/new"
    contract_length: "infinite"
    item_description: "Join Fit8Tube now,make your body strongest."
    content_url: "http://muk.fit8tube.com?s="
    register_url: "http://muk.fit8tube.com/adduser?sign=mgage_uk&username={user_name}"
    unsub_success_url: "http://muk.fit8tube.com/unsub/success"
    api_key: "7540fbdfc4990e47dbf2b82c9ca2f92ce68bdd34"
    limit_sub_num: 50
    camp_id: 11
  892-Vodafone:
    service_id: "892-Vodafone"
    service_code: "892"
    service_name: "Fit Body"
    version: 1
    merchant_id: 52
    share_key: "d81aaca1d338aa857f076171ef251775d019e738"
    amount: "450"
    period: "604800"
    aoc_url: "http://migpay.com/managed_subscriptions/new"
    contract_length: "infinite"
    item_description: "Join Fit8Tube now,make your body strongest."
    content_url: "http://muk.fit8tube.com?s="
    register_url: "http://muk.fit8tube.com/adduser?sign=mgage_uk&username={user_name}"
    unsub_success_url: "http://muk.fit8tube.com/unsub/success"
    api_key: "7540fbdfc4990e47dbf2b82c9ca2f92ce68bdd34"
    limit_sub_num: 50
    camp_id: 11
  892-Three:
    service_id: "892-Three"
    service_code: "892"
    service_name: "Fit Body"
    version: 1
    merchant_id: 52
    share_key: "d81aaca1d338aa857f076171ef251775d019e738"
    amount: "450"
    period: "604800"
    aoc_url: "http://migpay.com/managed_subscriptions/new"
    contract_length: "infinite"
    item_description: "Join Fit8Tube now,make your body strongest."
    content_url: "http://muk.fit8tube.com?s="
    register_url: "http://muk.fit8tube.com/adduser?sign=mgage_uk&username={user_name}"
    unsub_success_url: "http://muk.fit8tube.com/unsub/success"
    api_key: "7540fbdfc4990e47dbf2b82c9ca2f92ce68bdd34"
    limit_sub_num: 50
    camp_id: 12
  1036:
    service_id: "1036"
    service_code: "1036"
    service_name: "flingirls"
    merchant_id: 52
    version: 2
    share_key: "59fabc2ecce769c4b608c06ab1042a6f"
    amount: "450"
    period: "604800"
    aoc_url: "http://pay.mgage.com/nl/subscriptions/new"
    contract_length: "infinite"
    item_description: "join Flingirls now, watch the best sexy videos."
    content_url: "http://muk.flingirls.com?s="
    register_url: "http://muk.flingirls.com/adduser?sign=mgage_uk&username={user_name}"
    unsub_success_url: "http://muk.flingirls.com/unsub/success"
    api_key: "3e7e8accde5094818bda5e9d537129ea"
    limit_sub_num: 50
    camp_id: 52
  1036-Vodafone:
    service_id: "1036-Vodafone"
    service_code: "1036"
    service_name: "flingirls"
    version: 2
    merchant_id: 52
    share_key: "59fabc2ecce769c4b608c06ab1042a6f"
    amount: "450"
    period: "604800"
    aoc_url: "http://pay.mgage.com/nl/subscriptions/new"
    contract_length: "infinite"
    item_description: "join Flingirls now, watch the best sexy videos."
    content_url: "http://muk.flingirls.com?s="
    register_url: "http://muk.flingirls.com/adduser?sign=mgage_uk&username={user_name}"
    unsub_success_url: "http://muk.flingirls.com/unsub/success"
    api_key: "3e7e8accde5094818bda5e9d537129ea"
    limit_sub_num: 50
    camp_id: 52
  1036-Three:
    service_id: "1036-Three"
    service_code: "1036"
    service_name: "flingirls"
    version: 2
    merchant_id: 52
    share_key: "59fabc2ecce769c4b608c06ab1042a6f"
    amount: "450"
    period: "604800"
    aoc_url: "http://pay.mgage.com/nl/subscriptions/new"
    contract_length: "infinite"
    item_description: "join Flingirls now, watch the best sexy videos."
    content_url: "http://muk.flingirls.com?s="
    register_url: "http://muk.flingirls.com/adduser?sign=mgage_uk&username={user_name}"
    unsub_success_url: "http://muk.flingirls.com/unsub/success"
    api_key: "3e7e8accde5094818bda5e9d537129ea"
    limit_sub_num: 50
    camp_id: 52
  1037:
    service_id: "1037"
    service_code: "1037"
    service_name: "Holyzgame"
    merchant_id: 52
    version: 2
    share_key: "07aeabfb34027829a66bac8a9bd92cfb"
    amount: "450"
    period: "604800"
    aoc_url: "http://pay.mgage.com/nl/subscriptions/new"
    contract_length: "infinite"
    item_description: "Holyzgame,a unique entertainment center."
    content_url: "http://muk.holyzgame.com?s="
    register_url: "http://muk.holyzgame.com/adduser?sign=mgage_uk&username={user_name}"
    unsub_success_url: "http://muk.holyzgame.com/unsub/success"
    api_key: "107934853a936cf3fdebd3d463682b7e"
    limit_sub_num: 50
    camp_id: 54
  1037-Vodafone:
    service_id: "1037-Vodafone"
    service_code: "1037"
    service_name: "Holyzgame"
    merchant_id: 52
    version: 2
    share_key: "07aeabfb34027829a66bac8a9bd92cfb"
    amount: "450"
    period: "604800"
    aoc_url: "http://pay.mgage.com/nl/subscriptions/new"
    contract_length: "infinite"
    item_description: "Holyzgame,a unique entertainment center."
    content_url: "http://muk.holyzgame.com?s="
    register_url: "http://muk.fit8tube.com/adduser?sign=mgage_uk&username={user_name}"
    unsub_success_url: "http://muk.holyzgame.com/unsub/success"
    api_key: "107934853a936cf3fdebd3d463682b7e"
    limit_sub_num: 50
    camp_id: 54
  1037-Three:
    service_id: "1037-Three"
    service_code: "1037"
    service_name: "Holyzgame"
    version: 2
    merchant_id: 52
    share_key: "07aeabfb34027829a66bac8a9bd92cfb"
    amount: "450"
    period: "604800"
    aoc_url: "http://pay.mgage.com/nl/subscriptions/new"
    contract_length: "infinite"
    item_description: "Holyzgame,a unique entertainment center."
    content_url: "http://muk.holyzgame.com?s="
    register_url: "http://muk.fit8tube.com/adduser?sign=mgage_uk&username={user_name}"
    unsub_success_url: "http://muk.holyzgame.com/unsub/success"
    api_key: "107934853a936cf3fdebd3d463682b7e"
    limit_sub_num: 50
    camp_id: 0
